import type { TransactionDto } from "./types";

// Sample data used until the API is deployed.
// Replaced by real calls without touching the components.
// A single list of transactions: every figure on the dashboard is derived
// from it, so the summary, the breakdown and the chart can never disagree.

export const mockTransactions: TransactionDto[] = [
  {
    id: 1,
    description: "Nomina",
    amount: 2100,
    date: "2026-04-01",
    type: "Income",
    categoryId: 6,
    categoryName: "Salario",
  },
  {
    id: 2,
    description: "Alquiler",
    amount: 750,
    date: "2026-04-02",
    type: "Expense",
    categoryId: 1,
    categoryName: "Vivienda",
  },
  {
    id: 3,
    description: "Internet y movil",
    amount: 47.59,
    date: "2026-04-04",
    type: "Expense",
    categoryId: 4,
    categoryName: "Suministros",
  },
  {
    id: 4,
    description: "Supermercado",
    amount: 88.95,
    date: "2026-04-07",
    type: "Expense",
    categoryId: 2,
    categoryName: "Alimentacion",
  },
  {
    id: 5,
    description: "Gasolina",
    amount: 54.88,
    date: "2026-04-10",
    type: "Expense",
    categoryId: 3,
    categoryName: "Transporte",
  },
  {
    id: 6,
    description: "Suscripciones",
    amount: 26.34,
    date: "2026-04-13",
    type: "Expense",
    categoryId: 5,
    categoryName: "Ocio",
  },
  {
    id: 7,
    description: "Nomina",
    amount: 2100,
    date: "2026-05-01",
    type: "Income",
    categoryId: 6,
    categoryName: "Salario",
  },
  {
    id: 8,
    description: "Alquiler",
    amount: 750,
    date: "2026-05-02",
    type: "Expense",
    categoryId: 1,
    categoryName: "Vivienda",
  },
  {
    id: 9,
    description: "Suscripciones",
    amount: 25.03,
    date: "2026-05-04",
    type: "Expense",
    categoryId: 5,
    categoryName: "Ocio",
  },
  {
    id: 10,
    description: "Gasolina",
    amount: 54.35,
    date: "2026-05-07",
    type: "Expense",
    categoryId: 3,
    categoryName: "Transporte",
  },
  {
    id: 11,
    description: "Compra semanal",
    amount: 85.0,
    date: "2026-05-10",
    type: "Expense",
    categoryId: 2,
    categoryName: "Alimentacion",
  },
  {
    id: 12,
    description: "Electricidad",
    amount: 71.2,
    date: "2026-05-13",
    type: "Expense",
    categoryId: 4,
    categoryName: "Suministros",
  },
  {
    id: 13,
    description: "Nomina",
    amount: 2100,
    date: "2026-06-01",
    type: "Income",
    categoryId: 6,
    categoryName: "Salario",
  },
  {
    id: 14,
    description: "Alquiler",
    amount: 750,
    date: "2026-06-02",
    type: "Expense",
    categoryId: 1,
    categoryName: "Vivienda",
  },
  {
    id: 15,
    description: "Cena fuera",
    amount: 46.17,
    date: "2026-06-04",
    type: "Expense",
    categoryId: 2,
    categoryName: "Alimentacion",
  },
  {
    id: 16,
    description: "Gasolina",
    amount: 54.17,
    date: "2026-06-07",
    type: "Expense",
    categoryId: 3,
    categoryName: "Transporte",
  },
  {
    id: 17,
    description: "Internet y movil",
    amount: 57.92,
    date: "2026-06-10",
    type: "Expense",
    categoryId: 4,
    categoryName: "Suministros",
  },
  {
    id: 18,
    description: "Electricidad",
    amount: 61.84,
    date: "2026-06-13",
    type: "Expense",
    categoryId: 4,
    categoryName: "Suministros",
  },
  {
    id: 19,
    description: "Clase particular",
    amount: 120,
    date: "2026-06-18",
    type: "Income",
    categoryId: 7,
    categoryName: "Extras",
  },
  {
    id: 20,
    description: "Nomina",
    amount: 2100,
    date: "2026-07-01",
    type: "Income",
    categoryId: 6,
    categoryName: "Salario",
  },
  {
    id: 21,
    description: "Alquiler",
    amount: 750,
    date: "2026-07-02",
    type: "Expense",
    categoryId: 1,
    categoryName: "Vivienda",
  },
  {
    id: 22,
    description: "Gasolina",
    amount: 59.13,
    date: "2026-07-04",
    type: "Expense",
    categoryId: 3,
    categoryName: "Transporte",
  },
  {
    id: 23,
    description: "Compra semanal",
    amount: 86.81,
    date: "2026-07-07",
    type: "Expense",
    categoryId: 2,
    categoryName: "Alimentacion",
  },
  {
    id: 24,
    description: "Abono transporte",
    amount: 35.65,
    date: "2026-07-10",
    type: "Expense",
    categoryId: 3,
    categoryName: "Transporte",
  },
  {
    id: 25,
    description: "Cena fuera",
    amount: 41.96,
    date: "2026-07-13",
    type: "Expense",
    categoryId: 2,
    categoryName: "Alimentacion",
  },
  {
    id: 26,
    description: "Nomina",
    amount: 2100,
    date: "2026-08-01",
    type: "Income",
    categoryId: 6,
    categoryName: "Salario",
  },
  {
    id: 27,
    description: "Alquiler",
    amount: 750,
    date: "2026-08-02",
    type: "Expense",
    categoryId: 1,
    categoryName: "Vivienda",
  },
  {
    id: 28,
    description: "Supermercado",
    amount: 83.96,
    date: "2026-08-04",
    type: "Expense",
    categoryId: 2,
    categoryName: "Alimentacion",
  },
  {
    id: 29,
    description: "Cena fuera",
    amount: 42.94,
    date: "2026-08-07",
    type: "Expense",
    categoryId: 2,
    categoryName: "Alimentacion",
  },
  {
    id: 30,
    description: "Abono transporte",
    amount: 41.67,
    date: "2026-08-10",
    type: "Expense",
    categoryId: 3,
    categoryName: "Transporte",
  },
  {
    id: 31,
    description: "Electricidad",
    amount: 62.17,
    date: "2026-08-13",
    type: "Expense",
    categoryId: 4,
    categoryName: "Suministros",
  },
  {
    id: 32,
    description: "Nomina",
    amount: 2100,
    date: "2026-09-01",
    type: "Income",
    categoryId: 6,
    categoryName: "Salario",
  },
  {
    id: 33,
    description: "Alquiler",
    amount: 750,
    date: "2026-09-02",
    type: "Expense",
    categoryId: 1,
    categoryName: "Vivienda",
  },
  {
    id: 34,
    description: "Compra semanal",
    amount: 99.88,
    date: "2026-09-04",
    type: "Expense",
    categoryId: 2,
    categoryName: "Alimentacion",
  },
  {
    id: 35,
    description: "Gasolina",
    amount: 69.73,
    date: "2026-09-07",
    type: "Expense",
    categoryId: 3,
    categoryName: "Transporte",
  },
  {
    id: 36,
    description: "Cine",
    amount: 20.06,
    date: "2026-09-10",
    type: "Expense",
    categoryId: 5,
    categoryName: "Ocio",
  },
  {
    id: 37,
    description: "Internet y movil",
    amount: 64.41,
    date: "2026-09-13",
    type: "Expense",
    categoryId: 4,
    categoryName: "Suministros",
  },
  {
    id: 38,
    description: "Clase particular",
    amount: 120,
    date: "2026-09-18",
    type: "Income",
    categoryId: 7,
    categoryName: "Extras",
  },
];
